### ISSUE TITLE
404 https://igraph.org/python/doc/tutorial/tutorial.html#layouts-and-plotting

### ISSUE THREAD

**Issue by BaseMax** [igraph/igraph.org#56]
a broken link inside https://igraph.org/python/tutorial/0.9.6/visualisation.html page.

**Comment by ntamas** [comment]
Unfortunately it's unlikely that these broken links will be fixed; we have recently moved all the documentation of the Python interface to https://igraph.readthedocs.io, and the documentation of the old releases is there only for archival purposes. I hope that Google and other search engines will pick up the new location in the next few days and start indexing readthedocs instead of the old versions on igraph.org
